apiVersion: v1
kind: PersistentVolume
metadata:
  name: wict-app-pv
spec:
  capacity:
    storage: 60Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.9.21
    path: /nfs

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wict-app-pv
  namespace: kube-wict
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi